#!/bin/sh
#
# Initialize casperjs and load the IITC bot environment
#
AUTHFILE=$HOME/.config/iitcbot/authentication
COOKIES=$HOME/.local/share/iitcbot/cookies

if [ ! -d `dirname $COOKIES` ] ; then
   mkdir -p -m 700 `dirname $COOKIES`
fi

if [ ! -f $AUTHFILE ] ; then
   echo "ERROR: login information file $AUTHFILE not found" ; exit 2
fi

/usr/local/bin/casperjs --cookies-file=$COOKIES \
			--auth-file=$AUTHFILE \
			--web-security=false \
			--ignore-ssl-errors=true \
			iitc.js "$@" \
 | egrep -v --line-buffered "HTMLScriptElement is not a|refreshing chat"
